### ISSUE TITLE
per field attributes

### ISSUE THREAD

**Issue by seanmonstar** [erickt/rust-serde#13]
Brought up by WalrusPony in IRC. Fields in JSON may be conflict with keywords in Rust. One solution might be to append an attribute on a field, specifying the name that should be used in deriving.

```rust
#[deriving(Serializable, Deserializable)]
struct Foo {
    bar: u32,
    #[serde(name="mod")]
    mod_: String,
}
```

**Comment by hugoduncan** [comment]
This could also be useful if the json contains camel cased keys, and you would like to use snake case field names.

**Comment by erickt** [comment]
Done! Thanks @hugoduncan!
