### ISSUE TITLE
json enum deserialization needs an allocation

### ISSUE THREAD

**Issue by erickt** [erickt/rust-serde#29]
This is happening here: https://github.com/erickt/rust-serde/blob/master/serde2/src/json/de.rs#L424. Unfortunately we are passing both a `&self` and implicitly a `&mut self` to the caller. We'll probably need to change how `de::Visitor::visit_enum` works.

**Comment by oli-obk** [comment]
when using `visit_named_map` something similar happens in my case. maybe it needs to be split up into `visit_map_name` and `visit_map` (the latter already existing).

**Comment by erickt** [comment]
@oli-obk: can you point me to your code for reference?

**Comment by oli-obk** [comment]
The root-node parsing of an xml element. I made the root element have the name of the outermost struct that I'm parsing. This could&might get redesigned though. https://github.com/oli-obk/rust-serde/blob/xml/src/xml/de.rs#L184-185

**Comment by erickt** [comment]
@oli-obk: I landed a fix for the enum allocation, and tried to apply it to structs as well. Does that fix your problem?

**Comment by oli-obk** [comment]
Yes it does. Thanks!

**Comment by erickt** [comment]
@oli-obk: Great!
