### ISSUE TITLE
Conflicting implementations for trait `serde::de::EnumSeqVisitor`

### ISSUE THREAD

**Issue by hugoduncan** [erickt/rust-serde#32]
Adding the following to `test_de.rs` causes `error: conflicting implementations for trait serde::de::EnumSeqVisitor` on compilation:

```rust
#[derive(Debug, PartialEq)]
#[derive_deserialize]
enum Cmd{
    Args(Vec<String>),
    Arg0(String)
}
```

**Comment by erickt** [comment]
Shucks! I was trying to be too clever. Should be pretty simple to fix though.
