### ISSUE TITLE
Wrong type value in data reported as "expected value" at line 0 column 0

### ISSUE THREAD

**Issue by hugoduncan** [erickt/rust-serde#33]
When reading data that is the wrong type, the error reported is opaque, and doesn't give a valid location.  This makes debugging hard and makes it difficult to report meaningful errors to a user of a program.

An example of this is reading `{"a": "b"}` for `struct S {a: Option<u32>}`, but the issue seems to be more general than this particular example.

**Comment by erickt** [comment]
Yeah, that's coming from my fight to keep down on the number of type parameters and the borrow checker. One approach I just thought of is if we see a call to a `serde::de::Visitor` error, we catch it and update the placeholder location with the real location. That might not be too difficult.

**Comment by erickt** [comment]
This has been fixed in the JSON deserializer.
