### ISSUE TITLE
cannot parse into a sequence before knowing it's a sequence

### ISSUE THREAD

**Issue by oli-obk** [erickt/rust-serde#38]
I have structure `A` with a sequence field (vector) and want to parse some xml into it.

```rust
struct A {
    some_field: Vec<String>,
}
```

The following xml is the canonical way of expressing such a structure (see xsd `maxOccurs`)
```xml
<A>
    <some_field>Hi</some_field>
    <some_field>42</some_field>
    <some_field>This is a test!</some_field>
</A>
```

During parsing I don't know yet that a sequence is expected, so in the `visit_value` function of the `MapVisitor` I'd attempt to decode the first value ("55") to a sequence. This will fail out of the obvious reason that the `VecVisitor` expects the `visit_seq` function. I cannot implement all `visit_*` functions and return a single value vector, as this idea would fail at the second element, which can't be added to that vector (and would fail horribly for fixed-length sequences like tuples).

Would this be a situation where `Deserializer` should be extended (with a `visit_seq` function)? Or will something like that yield some problems that `libserialize` has?

**Comment by erickt** [comment]
That's a good idea. We should probably also add a `Deserializer::visit_map` while we're at it.

**Comment by oli-obk** [comment]
a `visit_map` would probably simplify my xml code enormously
