### ISSUE TITLE
Should I use Serde for `google-apis-rs` ?

### ISSUE THREAD

**Issue by Byron** [erickt/rust-serde#40]
Hi, 

Sorry for using the ticket system for something that clearly is a question ... but here I am.
It seems that *serde* could be the answer to [my problem](https://github.com/Byron/google-apis-rs/issues/29), and I wonder if you have any objections against my plan to switch all json encoding tasks to `serde`.

One objection could be something like: "don't do it - serde will be unsupported soon and is nothing more than a (failed) experiment !!" ?

I hope not, but wanted to be sure :) !

Thank you,
Sebastian

**Comment by Byron** [comment]
Actually there is no choice, and I am using it already !
It was already a great learning experience, as I was forced to dig into macros and compiler plugins a little more.
Without it, I would be totally lost, thanks for making `serde` in the first place !

**Comment by erickt** [comment]
Happy to help! Let me know if you run into any problems. Just to let you know I've been iterating a lot on it recently which changes some of the Apis, which I hope to have a new release out this weekend.

**Comment by Byron** [comment]
Great to hear ! Actually I have found two issues already - I will just list them here so we can figure out what to do with them. It's totally possible that I just don't know how to use `serde` correctly :).

### Problem 1 (*minor*)
When sending requests to the server as json, these may be partial, thus only a few fields are actually set. Optional fields are declared with `Option<_>` properties that are `None`. Currently they end up as `"field"=Null` in json, which is valid, but wastes space 

*Possible solution*: option to omit 'name=null' during serialize

### Problem 2 (**critical**)
 If I deserialize server replies to a respective `struct`, the said deserialization will fail if the server responds with all known AND *added* fields. There should be a way to say 'ignore extra fields' when deserializing. Otherwise my API will be out-of-date quickly thanks to it's growing inability to deserialize server responses.

*Possible solution*: option to ignore fields we don't have in target struct

Thanks for your input.

**Comment by erickt** [comment]
I filed #43 and #44 for these issues :)

**Comment by Byron** [comment]
Awesome :) ! Thanks !

**Comment by Byron** [comment]
By the way: You can see how a relatively uninitiated user (me) uses `serde` [on youtube](http://youtu.be/UZnV0X9L9Js).
