### ISSUE TITLE
struct field alias is a rename, not an alias

### ISSUE THREAD

**Issue by oli-obk** [erickt/rust-serde#47]
parsing
```json
{
    "a1": "some text",
    "a2": 42
}
```
to the following structure
```rust
    #[derive(PartialEq, Debug, Serialize, Deserialize)]
    struct A {
        a1: String,
        #[serde(alias="a3")]
        a2: i32,
    }
```

will fail, because serde completely replaces all instances of `a2` with `a3`. The keyword "alias" sounds to me more like both should be accepted.

Maybe this feature should simply be renamed to "rename"?

**Comment by erickt** [comment]
Fixed! Thanks again.
