### ISSUE TITLE
Implement support for default fields

### ISSUE THREAD

**Issue by kvark** [erickt/rust-serde#9]
Needed for https://github.com/kvark/scene-rs/tree/master/src/gltf

**Comment by hugoduncan** [comment]
Another approach might be to only allow `Option` type fields to be missing, and default them to `None`.

**Comment by erickt** [comment]
@kvark: ack! I just realized I haven't come up with a way to handle missing fields in serde2. I need to investigate how to get that to work :)

**Comment by erickt** [comment]
We now do have the ability for deserializers like json to represent missing fields as a null or `None` type. We can  do the same thing for deserializees if they want to call `Default` by adding an annotation in the same vein as `#[serde(alias=...)]`.

**Comment by erickt** [comment]
This has actually been done, but I'm leaving it open until we add a test case for it.
